/**
 * hosts.conf - Define monitored hosts here
 * This file is copied to /etc/icinga2/conf.d/ during setup.
 */

// The Icinga 2 master itself
object Host "localhost" {
  import "generic-host"

  address  = "127.0.0.1"
  address6 = "::1"

  vars.os = "Linux"
  vars.http_vhosts["http"] = {
    http_uri = "/icingaweb2"
  }
  vars.disks["disk"] = {}
  vars.disks["disk /"] = {
    disk_partitions = "/"
  }
  vars.notification["mail"] = {
    groups = [ "icingaadmins" ]
  }
}
